### ISSUE TITLE
Gradle plugin

### ISSUE THREAD

**Issue by binkley** [openrewrite/rewrite-checkstyle#5]
Your documentation at https://docs.openrewrite.org/java/checkstyle is fantastic.  I wish more projects were so straight-forward to use.

Do you have a Gradle plugin?  The docs only discuss a Maven plugin.

**Comment by jkschneider** [comment]
@binkley Indeed, it is available here: https://github.com/openrewrite/rewrite-gradle-plugin. Just haven't quite documented it all yet :). Thanks for the positive message.

**Comment by jkschneider** [comment]
Open issue on the docs page so we don't lose track of this: https://github.com/openrewrite/rewrite-docs/issues/1.
