### ISSUE TITLE
Documentation typos?

### ISSUE THREAD

**Issue by binkley** [openrewrite/rewrite-checkstyle#6]
The documentation at https://docs.openrewrite.org/java/checkstyle seems to have typos:
```
---
type: specs.openrewrite.org/v1beta/recipe
name: java.Checkstyle 
visitors:
  - 'org.openrewrite.checkstyle.*'
configure:
  org.openrewrite.checkstyle.*
    congFile: ${maven.multiModuleProjectDirectory}/checkstyle.xml
```

1. Shouldn't line 6 have a colon after `org.openrewrite.checkstyle.*`?
2. Is the property named `congFile` or `configFile`?  If the former, you might rename it for clarity to the reader/user

**Comment by jkschneider** [comment]
1. No, I think this is correct. the `configure` section is intended to be separate from the `visitors` section (the latter is just a list of included visitors).
2. Good catch, fixed this up! Thanks.
